name: Triggers

# Controls when the workflow will run (Triggers on every code push)
on:  # if someone opens pull request for main branch then this will triiger.
  pull_request:
    types:
      - opened
    branches:
      - 'main'
#workflow_dispatch
#[push]

jobs:
  trigger:   #job name
    # The type of virtual machine runner the job will run on
    runs-on: ubuntu-latest #github hosted runners
    steps:
        - name: main ebranch push
          run: echo "Manually dispatched."
      # - name: manual
      #   run: echo "Manually dispatched."
