name: Triggers

# Controls when the workflow will run (Triggers on every code push)
on:
  push:
    branches:
      - 'feature'
#workflow_dispatch
#[push]

jobs:
  trigger:   #job name
    # The type of virtual machine runner the job will run on
    runs-on: ubuntu-latest #github hosted runners
    steps:
        - name: featurebranch push
          run: echo "Manually dispatched."
      # - name: manual
      #   run: echo "Manually dispatched."
