name: Context demo

# Controls when the workflow will run (Triggers on every code push)
on: [push]
env:
  project: roboshop
  component: caatalogue
  environment: dev
jobs:
  github-context:   #job name
    # The type of virtual machine runner the job will run on
    runs-on: ubuntu-latest #github hosted runners
    outputs:
      image-version: ${{ steps.tag.outputs.value }}
    steps:
      - name: print info
        run: |
          echo "${{ toJson(github) }}"
      - name: print info about the 
        run: echo "branch name is:${{ github.ref_name }}"

      - name: acccess environment variables
        run: |
          echo "Project: $project"
          echo "componenetg is: $component"
          echo "environment is: $environment"
        #echo "${{ toJson(github) }}"

      - name: Print secrets
        run: |
          echo "secret value: ${{ secrets.DB_USER }}"
          echo "DB passeord is: ${{ secrets.DB_PASSWORD }}"

      - name: Print variables
        run: |
          echo "db_url is: ${{ vars.DB_URL}}"

      - name: image tag
        id: tag
        run: |
          echo "value=1.0.0" >> "$GITHUB_OUTPUT"
          echo "component=catalogue" >> "$GITHUB_OUTPUT"

      - name: previous step output
        run: | 
          echo "Image tag is ${{ steps.tag.outputs.value }}"
          echo "component is ${{ steps.tag.outputs.component }}"

      - name: github env #github env is useful only for within the same job
        run: echo "project=roboshop" >> $GITHUB_ENV

      - name: print github env
        run: echo "Project is $project"

  deploy:
    runs-on: ubuntu-latest
    needs: github-context # means depends on above job
    steps:
      - name: prints github env in another job
        run: echo "image-version is ${{ needs.github-context.outputs.image-version }}"

  scan:
    runs-on: ubuntu-latest
    steps:
    - name: scanning sonar qube
      run: echo "sonar-scan running.........."

    - name: print job context
      run: echo "${{ toJson(job) }}"