name: Context demo

# Controls when the workflow will run (Triggers on every code push)
on: [push]

jobs:
  github-context:   #job name
    # The type of virtual machine runner the job will run on
    runs-on: ubuntu-latest #github hosted runners
    steps:
      - name: print info about the 
        run: echo "${{ github.rep_name}}"
        #echo "${{ toJson(github) }}"