name: Context demo

# Controls when the workflow will run (Triggers on every code push)
on: [push]
env:
  project: roboshop
  component: caatalogue
  environment: dev
jobs:
  github-context:   #job name
    # The type of virtual machine runner the job will run on
    runs-on: ubuntu-latest #github hosted runners
    steps:
      - name: print info about the 
        run: echo "branch name is:${{ github.ref_name }}"

      - name: acccess environment variables
        run: |
          echo "Project: $project"
          echo "componenetg is: $component"
          echo "environment is: $environment"
        #echo "${{ toJson(github) }}"

      - name: Print secrets
        run: |
          echo "secret value: ${{ secrets.DB_USER }}"
          echo "DB passeord is: ${{ secrets.DB_PASSWORD }}"

      - name: Print variables
        run: |
          echo "db_url is: ${{ vars.DB_URL}}"

      - name: image tag
        id: tag
        run: echo "value=1.0.0" >> "$GITHUB_OUTPUT"

      - name: previous step output
        run: echo "Image tag is ${{ steps.tag.outputs.value }}"